#!/bin/bash
hyprpm add https://github.com/KZDKM/Hyprspace
hyprpm enable Hyprspace
hyprpm add https://github.com/outfoxxed/hy3
hyprpm update

cd && git clone https://github.com/ckaznable/hyprnavi.git
cd hyprnavi
cargo build --release
cd target/release 
sudo install -Dm755 hyprnavi "/usr/local/bin/hyprnavi"
cd && sudo rm -rf hyprnavi

cargo install --git https://github.com/donovanglover/hyprnome
