#!/bin/bash
sudo zypper in libwayland-egl1 libwayland-client0 libwayland-cursor0 gtk-doc vala gtk4-devel "pkgconfig(gobject-introspection-1.0)"
cd && git clone https://github.com/wmww/gtk4-layer-shell.git && cd gtk4-layer-shell
meson setup -Dexamples=true -Ddocs=true -Dtests=true build
ninja -C build
sudo ninja -C build install
sudo ldconfig
cd && sudo rm -rf gtk4-layer-shell
