#!/bin/bash
echo "Intalling Desktop Environment"
sleep 5
sudo zypper install aubio-tools adw-gtk3 adw-gtk3-dark atuin bat bluez-devel blueman btop cava cliphist ddcutil eza fastfetch file-roller fish fuzzel fzf gnome-themes-extras grim gtk2-engine-murrine hyprland hyprlock hypridle hyprpaper hyprpicker hyprpolkitagent imv inotify-tools jq kvantum-manager kvantum-qt5 kvantum-qt6 kvantum-themes kitty kitty-shell-integration kitty-terminfo lazygit libaubio-devel libnotify-devel libpulse-devel libqalculate-devel mpv nwg-drawer nwg-look papirus-icon-theme qt5ct qt6ct qt6-declarative-devel ripgrep rofi-wayland sassc sensors slurp socat starship stow swappy tealdeer thunar thunar-archive-plugin thunar-media-tags-plugin thunar-volman transmission-qt trash-cli tmux tuigreet  wl-screenrec xdg-desktop-portal-gtk xdg-desktop-portal-hyprland xdg-user-dirs xdg-user-dirs-gtk xwayland yazi zathura zathura-plugin-pdf-poppler zoxide zsh

 
