#!/bin/bash
echo "Installing Flatpak Apps"
sleep 5
flatpak install flathub io.github.zen_browser.zen
flatpak install flathub com.ticktick.TickTick
flatpak install flathub org.onlyoffice.desktopeditors
flatpak install flathub com.github.tchx84.Flatseal
flatpak install flathub org.js.nuclear.Nuclear
flatpak install flathub tv.kodi.Kodi
