#!/bin/bash
echo "@fonts"
sleep 5
sudo mkdir -p /usr/local/share/fonts/
sudo cp -R $HOME/git/.hyprdots/.fonts/* /usr/local/share/fonts/
sudo chown -R root: /usr/local/share/fonts/
sudo chmod 644 /usr/local/share/fonts/*
sudo fc-cache -v
